/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.register;

import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import top.r3944realms.eroticdungeongame.EroticDungeon;

public class EDGParticleTypes {
    public static final DeferredRegister<ParticleType<?>> PARTICLE_TYPES =
            DeferredRegister.create(ForgeRegistries.PARTICLE_TYPES, EroticDungeon.MOD_ID);
    // 注册自定义竖向横扫粒子
    public static final RegistryObject<SimpleParticleType> VERTICAL_WHIP_SWEEP =
            PARTICLE_TYPES.register("vertical_whip_sweep",
                    () -> new SimpleParticleType(true));

    // 注册自定义鞭痕粒子
    public static final RegistryObject<SimpleParticleType> WHIP_SCAR =
            PARTICLE_TYPES.register("whip_scar",
                    () -> new SimpleParticleType(true));
    public static void register(IEventBus bus) {
        PARTICLE_TYPES.register(bus);
    }
}
