///*
// *  Copyright 2025-2026 R3944Realms
// *
// *    Licensed under the Apache License, Version 2.0 (the "License");
// *    you may not use this file except in compliance with the License.
// *    You may obtain a copy of the License at
// *
// *        http://www.apache.org/licenses/LICENSE-2.0
// *
// *    Unless required by applicable law or agreed to in writing, software
// *    distributed under the License is distributed on an "AS IS" BASIS,
// *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// *    See the License for the specific language governing permissions and
// *    limitations under the License.
// */
//
//package top.r3944realms.eroticdungeongame.mixin.minecraft;
//
//import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
//import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
//import net.minecraft.client.multiplayer.ServerData;
//import net.minecraft.client.multiplayer.ServerStatusPinger;
//import net.minecraft.network.chat.Component;
//import org.spongepowered.asm.mixin.Mixin;
//import org.spongepowered.asm.mixin.Shadow;
//
//import java.util.List;
//
//@Mixin(ServerStatusPinger.class)
//public abstract class MixinServerStatusPinger {
//    @Shadow
//    static Component formatPlayerCount(int players, int capacity) {
//        return Component.empty();
//    }
//
//    @WrapMethod(
//            method = "pingServer"
//    )
//    private void edg$fakePing(ServerData server, Runnable serverListUpdater, Operation<Void> original) {
//        if ("v10.leisuretimedock.top".equalsIgnoreCase(server.ip)) {
//            server.motd = Component.literal("§aWelcome to the LTD server!");
//            server.version = Component.literal("1.20.1");
//            server.protocol = 763;
//            server.status = formatPlayerCount(0, 32);
//
//            server.playerList = List.of();
//
//            serverListUpdater.run();
//        } else original.call(server, serverListUpdater);
//    }
//}
