/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.content.recipe;

import com.google.gson.JsonObject;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.GsonHelper;
import net.minecraft.world.item.crafting.RecipeSerializer;
import org.jetbrains.annotations.NotNull;

public class SimpleDungeonRecipeSerializer<T extends DungeonRecipe> implements RecipeSerializer<T> {
    private final Factory<T> constructor;

    public SimpleDungeonRecipeSerializer(Factory<T> constructor) {
        this.constructor = constructor;
    }

    public @NotNull T fromJson(@NotNull ResourceLocation recipeId, @NotNull JsonObject serializedRecipe) {
        DungeonCraftingBookCategory craftingbookcategory = DungeonCraftingBookCategory.CODEC.byName(GsonHelper.getAsString(serializedRecipe, "category", null), DungeonCraftingBookCategory.MISC);
        return this.constructor.create(recipeId, craftingbookcategory);
    }

    public T fromNetwork(@NotNull ResourceLocation recipeId, @NotNull FriendlyByteBuf buffer) {
        DungeonCraftingBookCategory craftingbookcategory = buffer.readEnum(DungeonCraftingBookCategory.class);
        return this.constructor.create(recipeId, craftingbookcategory);
    }

    public void toNetwork(@NotNull FriendlyByteBuf buffer, @NotNull T recipe) {
        buffer.writeEnum(recipe.category());
    }

    @FunctionalInterface
    public interface Factory<T extends DungeonRecipe> {
        T create(ResourceLocation var1, DungeonCraftingBookCategory var2);
    }
}
