/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.register;

import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.content.recipe.DungeonKeyCopyRecipe;
import top.r3944realms.eroticdungeongame.content.recipe.DungeonShapedRecipe;
import top.r3944realms.eroticdungeongame.content.recipe.DungeonShapelessRecipe;
import top.r3944realms.eroticdungeongame.content.recipe.SimpleDungeonRecipeSerializer;

public class EDGRecipeSerializers {
    public static final DeferredRegister<RecipeSerializer<?>> RECIPE_SERIALIZERS = DeferredRegister.create(ForgeRegistries.RECIPE_SERIALIZERS, EroticDungeon.MOD_ID);

    public static final RegistryObject<RecipeSerializer<DungeonShapedRecipe>> SHAPED_DUNGEON_RECIPE = RECIPE_SERIALIZERS.register(
            "dungeon_shaped_recipe", DungeonShapedRecipe.Serializer::new
    );
    public static final RegistryObject<RecipeSerializer<DungeonShapelessRecipe>> DUNGEON_SHAPELESS_RECIPE = RECIPE_SERIALIZERS.register(
            "dungeon_shapeless_recipe", DungeonShapelessRecipe.Serializer::new
    );
    public static final RegistryObject<RecipeSerializer<DungeonKeyCopyRecipe>> DUNGEON_KEY_COPY = RECIPE_SERIALIZERS.register(
            "dungeon_key_copy_recipe", () -> new SimpleDungeonRecipeSerializer<>(DungeonKeyCopyRecipe::new)
    );

    public static void register(IEventBus eventBus) {
        RECIPE_SERIALIZERS.register(eventBus);
    }
}
