/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.content.block.blockentity;

import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.level.block.state.BlockState;
import org.jetbrains.annotations.NotNull;
import top.r3944realms.eroticdungeongame.content.entity.SeatEntity;
import top.r3944realms.eroticdungeongame.core.register.EDGBlockEntities;

public class PilloryBlockEntity extends BaseSeatBlockEntity {
    public PilloryBlockEntity(BlockPos blockPos, BlockState blockState) {
        super(EDGBlockEntities.PILLORY_BLOCK_ENTITY.get(), blockPos, blockState);
    }

    @Override
    public void passengerRot(@NotNull Entity passenger, @NotNull SeatEntity seat) {
        super.passengerRot(passenger, seat);
    }
}
