/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.device;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import top.r3944realms.eroticdungeongame.content.animation.EDGAnimation;
import top.r3944realms.eroticdungeongame.content.block.FurnitureShapeType;
import top.r3944realms.eroticdungeongame.content.entity.SeatEntity;

public interface ISeatType {
    FurnitureShapeType getFurnitureShapeType();

    boolean isOppositeDirection();

    Vec3 getFirstModelOffset();

    double getOffsetZ();

    double getOffsetY();

    double getOffsetX();

    Class<?> getBlockClass();

    float getYawOffset();

    float getEyeHeight();

    AABB getPlayerBB();

    @Nullable
    EDGAnimation getAnimation();

    @Contract()
    @NotNull
    String getName();

    @NotNull
    EntityType<SeatEntity> getEntityType();
}
