/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.api.capability;

import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.AABB;

/**
 * The interface Player dungeon data.
 */
public interface IPlayerDungeonData {
    /**
     * Sets device main block pos.
     *
     * @param pos the pos
     */
    void setDeviceMainBlockPos(BlockPos pos);

    /**
     * Gets device main block pos.
     *
     * @return the device main block pos
     */
    BlockPos getDeviceMainBlockPos();

    /**
     * Sets animation resource location.
     *
     * @param location the location
     */
    void setAnimationResourceLocation(ResourceLocation location);

    /**
     * Gets animation resource location.
     *
     * @return the animation resource location
     */
    ResourceLocation getAnimationResourceLocation();

    /**
     * Gets player bounding box.
     *
     * @return the player bounding box
     */
    AABB getPlayerBoundingBox();

    /**
     * Sets player bounding box.
     *
     * @param boundingBox the bounding box
     */
    void setPlayerBoundingBox(AABB boundingBox);

    /**
     * Gets eye height.
     *
     * @return the eye height
     */
    float getEyeHeight();

    /**
     * Sets eye height.
     *
     * @param eyeHeight the eye height
     */
    void setEyeHeight(float eyeHeight);
}
