/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.mixin.minecraft;

import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.mojang.blaze3d.vertex.PoseStack;
import net.minecraft.client.renderer.ItemInHandRenderer;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.item.ItemStack;
import org.spongepowered.asm.mixin.Mixin;
import top.r3944realms.eroticdungeongame.api.workspace.Services;
import top.r3944realms.eroticdungeongame.content.block.type.DisplayRackBlock;

@Mixin(ItemInHandRenderer.class)
public abstract class MixinItemInHandRenderer {

    @WrapMethod(
            method = "renderItem"
    )
    private void edg$removeItemInHandRender(
            LivingEntity entity, ItemStack itemStack, ItemDisplayContext displayContext, boolean leftHand, PoseStack poseStack, MultiBufferSource buffer, int seed, Operation<Void> original) {
        Services.WORK_SPACE.tryToDoIfInDevice(entity, data -> {
            if(data.getDeviceMainBlockPos() != null && !(entity.level().getBlockState(data.getDeviceMainBlockPos()).getBlock() instanceof DisplayRackBlock)) {
                original.call(entity, itemStack, displayContext, leftHand, poseStack, buffer, seed);
            }
        }, () -> original.call(entity, itemStack, displayContext, leftHand, poseStack, buffer, seed));
    }
}
