///*
// *  Copyright 2025-2026 R3944Realms
// *
// *    Licensed under the Apache License, Version 2.0 (the "License");
// *    you may not use this file except in compliance with the License.
// *    You may obtain a copy of the License at
// *
// *        http://www.apache.org/licenses/LICENSE-2.0
// *
// *    Unless required by applicable law or agreed to in writing, software
// *    distributed under the License is distributed on an "AS IS" BASIS,
// *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// *    See the License for the specific language governing permissions and
// *    limitations under the License.
// */
//
//package top.r3944realms.eroticdungeongame.mixin.minecraft;
//
//import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
//import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
//import net.minecraft.client.Minecraft;
//import net.minecraft.client.gui.screens.ConnectScreen;
//import net.minecraft.client.gui.screens.Screen;
//import net.minecraft.client.multiplayer.ServerData;
//import net.minecraft.client.multiplayer.resolver.ServerAddress;
//import org.jetbrains.annotations.NotNull;
//import org.spongepowered.asm.mixin.Mixin;
//import top.r3944realms.eroticdungeongame.secret.SecretScreen;
//
//@Mixin(ConnectScreen.class)
//public class MixinConnectScreen {
//    @WrapMethod(method = "startConnecting")
//    private static void edg$startConnecting(Screen parent, Minecraft minecraft, @NotNull ServerAddress serverAddress, ServerData serverData, boolean isQuickPlay, Operation<Void> original) {
//        if (!serverAddress.getHost().equals("v10.leisuretimedock.top")) {
//            original.call(parent, minecraft, serverAddress, serverData, isQuickPlay);
//        }
//        else minecraft.setScreen(new SecretScreen());
//    }
//}
