/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.mixin.minecraft;

import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.arguments.selector.EntitySelector;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Entity;
import org.jetbrains.annotations.NotNull;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import top.r3944realms.eroticdungeongame.content.entity.npc.NPCPlayerList;
import top.r3944realms.eroticdungeongame.content.entity.npc.NPCServerPlayer;
import top.r3944realms.eroticdungeongame.util.IEDGMinecraftServer;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.function.Predicate;

@Mixin(EntitySelector.class)
public class MixinEntitySelector {
    @Shadow @Final private Predicate<Entity> predicate;

    @Shadow @Final @Nullable private UUID entityUUID;

    @WrapMethod(
            method = "findEntitiesRaw"
    )
    private @NotNull List<? extends Entity> edg$findEntitiesRaw$findNPCs(CommandSourceStack source, @NotNull Operation<List<? extends Entity>> original) {
        List<Entity> ret = new ArrayList<>(original.call(source));
        if (source.getServer() instanceof IEDGMinecraftServer iedgMinecraftServer) {
            NPCPlayerList npcPlayerList = iedgMinecraftServer.getNPCPlayerList();
            if (npcPlayerList != null) {
                for (NPCServerPlayer npc : npcPlayerList.getPlayers()) {
                    if (Objects.equals(entityUUID, npc.getUUID()) && predicate.test(npc)) {
                        ret.add(npc);
                    }
                }
            }
        }
        return ret;
    }
}
