/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.compat;

import com.xtracr.realcamera.RealCameraCore;
import dev.tr7zw.firstperson.api.FirstPersonAPI;
import net.minecraft.client.Minecraft;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.ModList;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.api.EroticDungeonGameApi;
import top.r3944realms.lib39.core.compat.ICompat;

public class FirstPersonModelAndRealCameraCompat implements ICompat {
    public static FirstPersonModelAndRealCameraCompat INSTANCE = new FirstPersonModelAndRealCameraCompat();
    public static ResourceLocation ID = EroticDungeon.rl("firstperson_realcamera");
    public boolean initialize = false;
    @Override
    public void setInitialize(boolean initialize) {
        this.initialize = initialize;
    }

    @Override
    public boolean isInitialized() {
        return initialize;
    }

    @Override
    public ResourceLocation id() {
        return ID;
    }

    @Override
    public boolean isModLoaded() {
        return ModList.get().isLoaded("firstperson") && ModList.get().isLoaded("realcamera");
    }

    @Override
    public void initialize() {

    }

    @Override
    public void addClientGameListener(IEventBus gameBus) {
        gameBus.addListener(this::onClientTick);
    }

    @OnlyIn(Dist.CLIENT)
    private void onClientTick(TickEvent.ClientTickEvent event) {
        LocalPlayer player = Minecraft.getInstance().player;
        if (Minecraft.getInstance().options.getCameraType().isFirstPerson()) {
            if (EroticDungeonGameApi.isInDevice(player)) {
                FirstPersonAPI.setEnabled(true);
            } else if (RealCameraCore.isActive()) {
                FirstPersonAPI.setEnabled(false);
            }
        }
    }
}
