/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.datagen.builder;

import com.google.gson.JsonObject;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.crafting.RecipeSerializer;
import org.jetbrains.annotations.NotNull;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.content.recipe.DungeonCraftingBookCategory;
import top.r3944realms.eroticdungeongame.content.recipe.DungeonRecipe;

import javax.annotation.Nullable;
import java.util.function.Consumer;

public class DungeonSpecialRecipeBuilder extends DungeonCraftingRecipeBuilder {
    final RecipeSerializer<?> serializer;
    public DungeonSpecialRecipeBuilder(RecipeSerializer<?> serializer) {
        this.serializer = serializer;
    }

    public static DungeonSpecialRecipeBuilder special(RecipeSerializer<? extends DungeonRecipe> serializer) {
        return new DungeonSpecialRecipeBuilder(serializer);
    }
    public void save(Consumer<FinishedRecipe> finishedRecipeConsumer, final String id) {
        finishedRecipeConsumer.accept(new DungeonCraftingRecipeBuilder.CraftingResult(DungeonCraftingBookCategory.MISC) {
            public @NotNull RecipeSerializer<?> getType() {
                return DungeonSpecialRecipeBuilder.this.serializer;
            }

            public @NotNull ResourceLocation getId() {
                return EroticDungeon.rl(id);
            }

            @Nullable
            public JsonObject serializeAdvancement() {
                return null;
            }

            public ResourceLocation getAdvancementId() {
                return EroticDungeon.rl("");
            }
        });
    }
}
