package top.r3944realms.eroticdungeongame.mixin.minecraft;

import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.mojang.blaze3d.vertex.PoseStack;
import net.minecraft.client.renderer.ItemInHandRenderer;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.item.ItemStack;
import org.spongepowered.asm.mixin.Mixin;
import top.r3944realms.eroticdungeongame.api.workspace.Services;
import top.r3944realms.eroticdungeongame.content.block.type.DisplayRackBlock;

@Mixin(ItemInHandRenderer.class)
public abstract class MixinItemInHandRenderer {

    @WrapMethod(
            method = "renderItem"
    )
    private void removeItemInHandRender(
            LivingEntity entity, ItemStack itemStack, ItemDisplayContext displayContext, boolean leftHand, PoseStack poseStack, MultiBufferSource buffer, int seed, Operation<Void> original) {
        Services.WORK_SPACE.tryToDoIfInDevice(entity, data -> {
            if(data.getDeviceMainBlockPos() != null && !(entity.level().getBlockState(data.getDeviceMainBlockPos()).getBlock() instanceof DisplayRackBlock)) {
                original.call(entity, itemStack, displayContext, leftHand, poseStack, buffer, seed);
            }
        }, () -> original.call(entity, itemStack, displayContext, leftHand, poseStack, buffer, seed));
    }
}
