/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.network.toServer;

import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.network.NetworkEvent;
import org.jetbrains.annotations.NotNull;
import top.r3944realms.eroticdungeongame.content.animation.IEDGAnimation;

import java.util.UUID;
import java.util.function.Supplier;

public record RefreshPlayerAnimationPacket(UUID uuid) {
    public RefreshPlayerAnimationPacket(@NotNull FriendlyByteBuf buf) {
        this(buf.readUUID());
    }
    public void encode(@NotNull FriendlyByteBuf buf) {
        buf.writeUUID(uuid);
    }

    public void handle(@NotNull Supplier<NetworkEvent.Context> contextSupplier) {
        NetworkEvent.Context context = contextSupplier.get();
        ServerPlayer sender = context.getSender();
        context.enqueueWork(() -> {
            if (sender != null) {
                if (sender.serverLevel().getEntity(uuid) instanceof ServerPlayer target) {
                    IEDGAnimation.refresh(target, sender);
                }
            }
        });
        context.setPacketHandled(true);
    }
}
