/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.network;

import net.minecraftforge.network.NetworkDirection;
import net.minecraftforge.network.NetworkRegistry;
import net.minecraftforge.network.simple.SimpleChannel;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.core.network.toServer.OffsetConfigPacket;
import top.r3944realms.eroticdungeongame.core.network.toServer.RequestQuitDevicePacket;

import java.util.concurrent.atomic.AtomicInteger;

public class EDGNetworkHandler {
    public static final SimpleChannel CHANNEL = NetworkRegistry.newSimpleChannel(
                    EroticDungeon.rl("main"),
            () -> EroticDungeon.ModInfo.VERSION,
            EroticDungeon.ModInfo.VERSION::equals,
            EroticDungeon.ModInfo.VERSION::equals
    );
   static AtomicInteger cid = new AtomicInteger(0);
    public static void register() {
        CHANNEL.messageBuilder(OffsetConfigPacket.class, getIndex(), NetworkDirection.PLAY_TO_SERVER)
                .encoder(OffsetConfigPacket::encode)
                .decoder(OffsetConfigPacket::new)
                .consumerMainThread(OffsetConfigPacket::handle)
                .add();
        CHANNEL.messageBuilder(RequestQuitDevicePacket.class, getIndex(), NetworkDirection.PLAY_TO_SERVER)
                .encoder(RequestQuitDevicePacket::encode)
                .decoder(RequestQuitDevicePacket::new)
                .consumerMainThread(RequestQuitDevicePacket::handle)
                .add();
    }
    public static int getIndex() {
        return cid.getAndIncrement();
    }
}
