package top.r3944realms.eroticdungeongame.content.register;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.content.block.blockentity.SeatBlockEntity;

public class EDGBlockEntities {
    public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, EroticDungeon.MOD_ID);
    @SuppressWarnings("DataFlowIssue")
    public static final RegistryObject<BlockEntityType<SeatBlockEntity>> SEAT_BLOCK_ENTITY = BLOCK_ENTITIES.register("seat_block_entity",
            () -> BlockEntityType.Builder
                    .of(SeatBlockEntity::new, EDGBlocks.CUFF_BED.get())
                    .build(null)
    );
    public static void register(IEventBus eventBus) {
        BLOCK_ENTITIES.register(eventBus);
    }

}
