/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.register;

import net.minecraft.world.entity.player.Player;
import net.minecraftforge.common.capabilities.RegisterCapabilitiesEvent;
import net.minecraftforge.event.AttachCapabilitiesEvent;
import org.jetbrains.annotations.NotNull;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.content.capability.AbstractPlayerDungeonData;
import top.r3944realms.eroticdungeongame.content.capability.PlayerDungeonDataProvider;

public class EDGCapabilities {

    public static final String DUNGEON_DATA = "dungeon_data";

    public static void registerCapability(@NotNull RegisterCapabilitiesEvent event) {
        event.register(AbstractPlayerDungeonData.class);
    }

    public static void attachCapability(@NotNull AttachCapabilitiesEvent<?> event) {
        if (event.getObject() instanceof Player player) {
            event.addCapability(EroticDungeon.rl(DUNGEON_DATA), new PlayerDungeonDataProvider(player));
        }
    }
}
