/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.network;

import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.network.NetworkDirection;
import net.minecraftforge.network.NetworkRegistry;
import net.minecraftforge.network.PacketDistributor;
import net.minecraftforge.network.simple.SimpleChannel;
import net.minecraftforge.server.ServerLifecycleHooks;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.core.network.toClient.NPCInfoRemovePacket;
import top.r3944realms.eroticdungeongame.core.network.toClient.NPCInfoUpdatePacket;
import top.r3944realms.eroticdungeongame.core.network.toServer.LoveMachineConfigPacket;
import top.r3944realms.eroticdungeongame.core.network.toServer.RefreshPlayerAnimationPacket;
import top.r3944realms.eroticdungeongame.core.network.toServer.RequestQuitDevicePacket;
import top.r3944realms.eroticdungeongame.core.network.toServer.SignArmorUpdatePacket;
import top.r3944realms.eroticdungeongame.util.IEDGMinecraftServer;

import java.util.concurrent.atomic.AtomicInteger;

public class EDGNetworkHandler {
    public static final PacketDistributor<Void> ALL_PLAYER = new PacketDistributor<>((voidPacketDistributor, supplier) ->  {
        MinecraftServer minecraftServer = ServerLifecycleHooks.getCurrentServer();
        if (minecraftServer instanceof IEDGMinecraftServer iedgMinecraftServer) {
           return packet -> iedgMinecraftServer.getNPCPlayerList().broadcastAll(packet);
        }
        return p -> {};
    }, NetworkDirection.PLAY_TO_CLIENT);
    public static final SimpleChannel CHANNEL = NetworkRegistry.newSimpleChannel(
                    EroticDungeon.rl("main"),
            () -> EroticDungeon.ModInfo.VERSION,
            EroticDungeon.ModInfo.VERSION::equals,
            EroticDungeon.ModInfo.VERSION::equals
    );
   static AtomicInteger cid = new AtomicInteger(0);
    public static void register() {
        CHANNEL.messageBuilder(LoveMachineConfigPacket.class, getIndex(), NetworkDirection.PLAY_TO_SERVER)
                .encoder(LoveMachineConfigPacket::encode)
                .decoder(LoveMachineConfigPacket::new)
                .consumerMainThread(LoveMachineConfigPacket::handle)
                .add();
        CHANNEL.messageBuilder(RequestQuitDevicePacket.class, getIndex(), NetworkDirection.PLAY_TO_SERVER)
                .encoder(RequestQuitDevicePacket::encode)
                .decoder(RequestQuitDevicePacket::new)
                .consumerMainThread(RequestQuitDevicePacket::handle)
                .add();
        CHANNEL.messageBuilder(NPCInfoRemovePacket.class, getIndex(), NetworkDirection.PLAY_TO_CLIENT)
                .encoder(NPCInfoRemovePacket::write)
                .decoder(NPCInfoRemovePacket::new)
                .consumerMainThread(NPCInfoRemovePacket::handle)
                .add();
        CHANNEL.messageBuilder(NPCInfoUpdatePacket.class, getIndex())
                .encoder(NPCInfoUpdatePacket::write)
                .decoder(NPCInfoUpdatePacket::new)
                .consumerMainThread(NPCInfoUpdatePacket::handle)
                .add();
        CHANNEL.messageBuilder(RefreshPlayerAnimationPacket.class, getIndex(), NetworkDirection.PLAY_TO_SERVER)
                .encoder(RefreshPlayerAnimationPacket::encode)
                .decoder(RefreshPlayerAnimationPacket::new)
                .consumerMainThread(RefreshPlayerAnimationPacket::handle)
                .add();
        CHANNEL.messageBuilder(SignArmorUpdatePacket.class, getIndex(), NetworkDirection.PLAY_TO_SERVER)
                .encoder(SignArmorUpdatePacket::encode)
                .decoder(SignArmorUpdatePacket::new)
                .consumerMainThread(SignArmorUpdatePacket::handle)
                .add();
    }
    public static int getIndex() {
        return cid.getAndIncrement();
    }

    public static <MSG> void sendToPlayer(MSG message, ServerPlayer player){
        CHANNEL.send(PacketDistributor.PLAYER.with(() -> player), message);
    }

    public static <MSG> void sendToAllPlayer(MSG message){
        CHANNEL.send(ALL_PLAYER.noArg(), message);
    }
    public static <MSG> void sendToServer(MSG message){
        CHANNEL.sendToServer(message);
    }
}
