package top.r3944realms.eroticdungeongame;

import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import top.r3944realms.eroticdungeongame.content.register.EDGBlockEntities;
import top.r3944realms.eroticdungeongame.content.register.EDGBlocks;
import top.r3944realms.eroticdungeongame.content.register.EDGCreativeTabs;
import top.r3944realms.eroticdungeongame.content.register.EDGEntities;

@Mod(EroticDungeon.MOD_ID)
public class EroticDungeon {
    public static final String MOD_ID = "eroticdungeongame";
    public static final Logger LOGGER = LoggerFactory.getLogger(EroticDungeon.class);
    public EroticDungeon() {
        IEventBus eventBus = FMLJavaModLoadingContext.get().getModEventBus();
        initialize(eventBus);
    }
    public static void initialize(IEventBus eventBus) {
        EDGBlocks.register(eventBus);
        EDGBlockEntities.register(eventBus);
        EDGCreativeTabs.register(eventBus);
        EDGEntities.register(eventBus);
    }
    public static ResourceLocation rl(String path) {
        return new ResourceLocation(MOD_ID, path);
    }
}
