/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.compat;

import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.ModList;
import org.jetbrains.annotations.NotNull;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.core.register.EDGCreativeTabs;
import top.r3944realms.eroticdungeongame.core.register.EDGItems;
import top.r3944realms.lib39.core.compat.IForgeCompat;

public class TouhouLittleMaidCompat implements IForgeCompat {
    public static TouhouLittleMaidCompat INSTANCE = new TouhouLittleMaidCompat();
    public static ResourceLocation ID = EroticDungeon.rl("touhou_little_maid");
    public boolean initialize = false;
    @Override
    public void setInitialize(boolean initialize) {
        this.initialize = initialize;
    }

    @Override
    public boolean isInitialized() {
        return initialize;
    }

    @Override
    public ResourceLocation id() {
        return ID;
    }

    @Override
    public boolean isModLoaded() {
        return ModList.get().isLoaded("touhou_little_maid");
    }

    @Override
    public void initialize() {

    }

    @Override
    public void addCommonModListener(@NotNull IEventBus modBus) {
        modBus.addListener(this::addItemToCreativeTab);
    }

    private void addItemToCreativeTab(@NotNull BuildCreativeModeTabContentsEvent event) {
        if (event.getTab().equals(EDGCreativeTabs.MAIN.get())) {
            event.accept(EDGItems.FILTER);
        }
    }
}
