/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.mixin.minecraft;

import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.mojang.blaze3d.vertex.PoseStack;
import net.minecraft.client.Camera;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.GameRenderer;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import top.r3944realms.eroticdungeongame.api.workspace.Services;

@Mixin(GameRenderer.class)
public class MixinGameRender {
    @Shadow @Final
    Minecraft minecraft;

    @WrapMethod(
            method = "renderItemInHand"
    )
    private void warpRenderHand(PoseStack poseStack, Camera activeRenderInfo, float partialTicks, Operation<Void> original) {
        Services.WORK_SPACE.tryToDoIfInDevice(minecraft.player, data -> {}, () -> original.call(poseStack, activeRenderInfo, partialTicks));
    }
}
