package top.r3944realms.eroticdungeongame.content.register;

import net.minecraft.world.level.block.Block;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.content.block.HorizontalDoubleSeatBlock;
import top.r3944realms.lib39.util.block.BlockRegistryBuilder;

import java.util.ArrayList;
import java.util.List;

public class EDGBlocks {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, EroticDungeon.MOD_ID);
    public static final List<RegistryObject<Block>> SEAT_BLOCKS = new ArrayList<>();
    public static final RegistryObject<Block> CUFF_BED =
            BlockRegistryBuilder
                    .create()
                    .withName("cuff_bed")
                    .registerBlock(BLOCKS, HorizontalDoubleSeatBlock::new)
                    .build();
    static {
        SEAT_BLOCKS.add(CUFF_BED);
    }
    public static void register(IEventBus eventBus) {
        BLOCKS.register(eventBus);
    }
}
