/*
 *  Copyright 2025-2026 R3944Realms
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package top.r3944realms.eroticdungeongame.core.register;

import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import top.r3944realms.eroticdungeongame.EroticDungeon;
import top.r3944realms.eroticdungeongame.content.entity.SeatEntity;

public class EDGEntities {
    public static final DeferredRegister<EntityType<?>> ENTITIES = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, EroticDungeon.MOD_ID);
    public static final RegistryObject<EntityType<SeatEntity>> SEAT = registerSeat(SeatEntity::new);

    private static <T extends Entity> RegistryObject<EntityType<T>> registerSeat(EntityType.EntityFactory<T> entityFactory) {
        return ENTITIES.register("seat", () -> EntityType.Builder
                .of(entityFactory, MobCategory.MISC)
                .sized(0.0f, 0.0f)
                .updateInterval(4)
                .build(EroticDungeon.rl("seat").toString()));
    }
    public static void register(IEventBus eventBus) {
        ENTITIES.register(eventBus);
    }

}
